[profile.default]
src = "src/contracts"
test = "test/foundry"
script = "script/foundry"
libs = ["lib"]
cache_path = "cache/foundry"
out = "artifacts/foundry"
broadcast = "tx_broadcast"

solc = "0.8.23"
solc_version = "0.8.23"
evm_version = "paris"
via_ir = false
optimizer_runs = 200

auto_detect_remappings = false
dynamic_test_linking = true
verbosity = 3

[profile.ci]
verbosity = 4
