version: "3.44"

dotenv:
    - .env

vars:
    SOLC_VERSION: v0.8.23

tasks:
    ensure-var:
        silent: true
        vars:
            PNAME: "{{index .CLI_ARGS_LIST 0}}"
            PVAL: "{{index .CLI_ARGS_LIST 1}}"
        cmd: '{{if eq (len .PVAL) 0}}echo ''Required arg "{{.PNAME}}" is not set'';exit 1{{else}}echo {{.PVAL}}{{end}}'

    deps:ts:
        desc: Install TypeScript dependencies
        aliases:
            - install:ts
        sources:
            - package.json
            - bun.lock
        cmd: bun install {{.CLI_ARGS}}

    deps:sol:
        desc: Install Solidity dependencies
        aliases:
            - install:sol
        sources:
            - .gitmodules
        generates:
            - lib/*/**/*
        cmd: forge install --shallow {{.CLI_ARGS}}

    deps:
        desc: Install all (Foundry/TS) dependencies
        aliases:
            - install
        deps:
            - deps:ts
            - deps:sol

    format:ts:
        desc: Run prettier formatter for TypeScript
        aliases:
            - fmt:ts
        cmd: bunx prettier --write .

    format:sol:
        desc: Run foundry formatter for Solidity
        aliases:
            - fmt:sol
        cmd: forge fmt
