version: "3.44"

dotenv:
    - .env

vars:
    SOLC_VERSION: v0.8.23

tasks:
    ensure-var:
        silent: true
        vars:
            PNAME: "{{index .CLI_ARGS_LIST 0}}"
            PVAL: "{{index .CLI_ARGS_LIST 1}}"
        cmd: '{{if eq (len .PVAL) 0}}echo ''Required arg "{{.PNAME}}" is not set'';exit 1{{else}}echo {{.PVAL}}{{end}}'

