[profile.default]
src = "src/contracts"
test = "test/foundry"
script = "script/foundry"
libs = ["lib"]
cache_path = "cache/foundry"
out = "artifacts/foundry"
broadcast = "tx_broadcast"

solc = "{{.Scaffold.solc_version}}"
solc_version = "{{.Scaffold.solc_version}}"
evm_version = "{{.Scaffold.evm_version}}"
via_ir = false
optimizer_runs = 200

auto_detect_remappings = false
dynamic_test_linking = true
verbosity = 3

[profile.ci]
verbosity = 4

## Solidity "style" settings such as linter, formatter and doc gen

[lint]
ignore = [
    "lib",
    "node_modules"
]
exclude_lints = [
    "unaliased-plain-import",
    "asm-keccak256"
]

[fmt]
ignore = [
    "lib",
    "node_modules"
]
single_line_statement_blocks = "multi"
multiline_func_header = "params_first"
sort_imports = false
contract_new_lines = false
override_spacing = true
line_length = 80
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
hex_underscore = "remove"
wrap_comments = false

[doc]
out = "docs/solidity"
title = "{{ .Project }} Docs"
ignore = [
    "node_modules",
    "test"
]
