version: "3.44"

dotenv:
    - .env

vars:
    SOLC_VERSION: "{{.Scaffold.solc_version}}"

tasks:
    #######################################################
    # Dependency Installation
    #######################################################

    deps:ts:
        desc: Install TypeScript dependencies
        aliases:
            - install:ts
        cmds:
            - task: internal:install:deps:ts
              vars:
                PACKAGE_NAMES: "{{.CLI_ARGS}}"

    deps:sol:
        desc: Install Solidity dependencies
        aliases:
            - install:sol
        cmds:
            - task: internal:install:deps:sol
              vars:
                PACKAGE_NAMES: "{{.CLI_ARGS}}"

    deps:all:
        desc: Install all (Foundry/TS) dependencies
        aliases:
            - install
            - deps
        deps:
            - internal:install:deps:ts
            - internal:install:deps:sol

    #######################################################
    # Formatting and Linting
    #######################################################

    format:ts:
        desc: Run prettier formatter for TypeScript
        aliases:
            - fmt:ts
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "prettier --write ."

    format:sol:
        desc: Run foundry formatter for Solidity
        aliases:
            - fmt:sol
        cmd: forge fmt

    format:
        desc: Format all sources (Solidity and TypeScript)
        aliases:
            - fmt
        deps:
            - format:ts
            - format:sol

    lint:ts:
        desc: Lint TypeScript files
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "eslint ."
                
    lint:ts:fix:
        desc: Lint and fix TypeScript files
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "eslint . --fix"
                
    lint:ts:check:
        desc: Lint check only
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "prettier --check ."

    lint:sol:
        desc: Lint Solidity files
        cmd: forge lint

    lint:
        desc: Lint all sources (Solidity and TypeScript)
        deps:
            - lint:ts
            - lint:sol

    #######################################################
    # Solidity Compilation
    #######################################################

    build:sol:
        desc: Compile smart contracts using both Foundry and Hardhat. Accepts CLI args for `forge compile`
        aliases:
            - build
            - compile
        cmds:
            - task: internal:build:sol
              vars:
                FORGS_ARGS: "{{.CLI_ARGS}}"

    flatten:hardhat:
        desc: Flatten given Solidity source code(s) using Hardhat. Check `task --summary flatten:hardhat` for more info on the usage
        summary: |
            Flatten given Solidity source code(s) using `hardhat flatten`.
            You must supply the input file(s) using task CLI args.

            If no output option is passed, flattened file will be printed in STDOUT.
            Use --output [file] to put contents into a file.

            Example:
                `task flatten:hardhat -- src/contracts/Airdrop.sol` - Prints the flattened contents in STDOUT
                `task flatten:hh -- src/contracts/Airdrop.sol --output SC.sol` - Writes to SC.sol
        silent: true
        aliases:
            - flatten:hh
        deps:
            - deps:all
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "hardhat flatten {{.CLI_ARGS}}"

    flatten:forge:
        desc: Flatten given Solidity source code using Foundry. Check `task --summary flatten:forge` for more info on the usage
        summary: |
            Flatten given Solidity source code(s) using `forge flatten`.
            You must supply the input file(s) using task CLI args.

            If no output option is passed, flattened file will be printed in STDOUT.
            Use --output [file] to put contents into a file.

            Examples:
                `task flatten:forge -- src/contracts/Airdrop.sol` - Prints the flattened contents in STDOUT
                `task flatten -- src/contracts/Airdrop.sol --output SC.sol` - Writes to SC.sol
        silent: true
        aliases:
            - flatten:f
            - flatten
        deps:
            - internal:build:sol
        cmds:
            - forge flatten {{.CLI_ARGS}}

    abi:forge:
        desc: Get contract ABI from Foundry artifacts. Pass contract name (without .sol or path) as CLI arg
        summary: |
            Get contract ABI from Foundry artifacts. Pass contract name (without .sol or path) as CLI arg

            Examples:
                `task abi -- Airdrop`
                `task abi -- Ownable`
        silent: true
        aliases:
            - abi:f
            - abi
        deps:
            - internal:build:sol
        cmds:
            - task: internal:get-foundry-artifact
              vars:
                SC_NAME: "{{.CLI_ARGS}}"
                JQ_PATH: ".abi"

    bytecode:forge:
        desc: Get contract bytecode from Foundry artifacts. Pass contract name (without .sol or path) as CLI arg
        summary: |
            Get contract bytecode from Foundry artifacts. Pass contract name (without .sol or path) as CLI arg

            Examples:
                `task bytecode:forge -- Airdrop`
                `task bytecode -- Ownable`
        silent: true
        aliases:
            - bytecode
            - bytecode:f
        deps:
            - internal:build:sol
        cmds:
            - task: internal:get-foundry-artifact
              vars:
                SC_NAME: "{{.CLI_ARGS}}"
                JQ_PATH: ".bytecode.object"

    abi:hardhat:
        desc: Get contract ABI from Hardhat artifacts. Pass contract path as CLI arg relative to remappings
        summary: |
            Get contract ABI from Hardhat artifacts. Pass contract path as CLI arg relative to remappings

            Examples:
                `task abi:hardhat -- src/contracts/Airdrop.sol`
                `task abi:hardhat -- openzeppelin/contracts/access/Ownable.sol`
        silent: true
        aliases:
            - abi:hh
        deps:
            - internal:build:sol
        cmds:
            - task: internal:get-hardhat-artifact
              vars:
                SC_NAME: "{{.CLI_ARGS}}"
                JQ_PATH: ".abi"

    bytecode:hardhat:
        desc: Get contract bytecode from Hardhat artifacts. Pass contract path as CLI arg relative to remappings
        summary: |
            Get contract bytecode from Hardhat artifacts. Pass contract path as CLI arg relative to remappings

            Examples:
                `task bytecode:hardhat -- src/contracts/Airdrop.sol`
                `task bytecode:hh -- openzeppelin/contracts/access/Ownable.sol`
        silent: true
        aliases:
            - bytecode:hh
        deps:
            - internal:build:sol
        cmds:
            - task: internal:get-hardhat-artifact
              vars:
                SC_NAME: "{{.CLI_ARGS}}"
                JQ_PATH: ".bytecode"

    #######################################################
    # Unit Test
    #######################################################

    test:forge:
        desc: Run Foundry unit tests. Accepts CLI args for `forge test`
        summary: |
            Run Foundry unit tests. Accepts CLI args for `forge test`

            Example:
                `task test -- --mc Airdrop` - Run tests only with "Airdrop" as their contract name
        aliases:
            - test
            - test:f
        deps:
            - internal:build:sol
        cmds:
            - forge test --show-progress --summary --detailed --ffi {{.CLI_ARGS}}

    test:hardhat:
        desc: Run Hardhat tests. Accepts CLI args for `hardhat test`
        summary: |
            Run Hardhat tests. Accepts CLI args for `hardhat test`

            Examples:
                `task test:hardhat` - Run all hardhat tests at `test/hardhat`
                `task test:hardhat -- test/hardhat/AirdropIntegration.test.ts` - Run only the test at given path
        aliases:
            - test:hh
        deps:
            - internal:build:sol
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "hardhat test mocha {{.CLI_ARGS}}"

    test:ts:
        desc: Run bun tests, without hardhat or foundry loaded. Make sure to limit path to `test/ts`. Accepts CLI args for `bun test`
        cmds: 
            - task: internal:test:ts
              vars:
                TEST_PATHS: "{{.CLI_ARGS}}"

    test:all:
        desc: Run all unit tests (Solidity and TypeScript)
        cmds:
            - task: test:forge
            - task: test:hardhat
            - task: internal:test:ts
              vars:
                TEST_PATHS: "[[.Computed.jpm_test_files]]"

    #######################################################
    # Node and REPL
    #######################################################

    node:anvil:
        desc: Run an Anvil node locally
        cmd: anvil -b 13 --accounts 1 {{.CLI_ARGS}}

    node:anvil:state:
        desc: Run an Anvil node forking another network with persistent storage
        cmd: task node:anvil --  --state cache/anvil/state.json --preserve-historical-states -s 13 {{.CLI_ARGS}}

    node:hardhat:
        desc: Run a Hardhat node locally
        deps:
            - internal:install:deps:ts
        cmds: 
            - task: internal:jpmx
              vars:
                X_ARGS: "hardhat node {{.CLI_ARGS}}"

    repl:hardhat:
        desc: Run the Hardhat console
        aliases:
            - repl:ts
            - console
        deps:
            - internal:install:deps:ts
            - internal:install:deps:sol
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "hardhat node {{.CLI_ARGS}}"

    repl:chisel:
        desc: Run chisel
        aliases:
            - repl:sol
        cmd: chisel {{.CLI_ARGS}}

    #######################################################
    # Scripts
    #######################################################

    deploy:
        desc: Run Foundry deploy script. Check `task --summary deploy` for full explanation and examples.
        summary: |
            To use this, you must sacrifice your soul

            Add deploy script to `script/foundry/`

            It will run forge script broadcast with given env var file

            Make sure your env file is up to date ok?

            Examples:
                `task deploy -- ANVIL local Deploy_Airdrop`
                `task deploy -- ETHEREUM_MAINNET mainnet Deploy_Airdrop --verify`
        vars:
            NETWORK:
                sh: task internal:ensure-arg -- "network name" {{index .CLI_ARGS_LIST 0}}
            WALLET_NAME:
                sh: task internal:ensure-arg -- "wallet name" {{index .CLI_ARGS_LIST 1}}
            SC_NAME:
                sh: task internal:ensure-arg -- "contract name" {{index .CLI_ARGS_LIST 2}}
            EXT_ARGS: '{{slice .CLI_ARGS_LIST 3 | join " "}}'
            RPC: "${{.NETWORK}}_RPC"
            API_KEY: "${{.NETWORK}}_API_KEY"
            ETHERSCAN_API_KEY: '{{if (.CLI_ARGS_LIST | has "--verify")}}--etherscan-api-key {{.API_KEY}}{{end}}'
            CHAINID: "${{.NETWORK}}_CHAINID"
        cmd: forge script --keystore .keystore/{{.WALLET_NAME}} --chain-id {{.CHAINID}} --rpc-url {{.RPC}} --broadcast -vvvv {{.ETHERSCAN_API_KEY}} {{.EXT_ARGS}} {{.SC_NAME}}

    script:hardhat:
        desc: Run a Hardhat script. Accepts CLI args
        aliases:
            - script
        deps:
            - internal:build:sol
        cmds:
            - task: internal:jpmx
              vars:
                X_ARGS: "hardhat run {{.CLI_ARGS}}"

    #######################################################
    # Verification
    #######################################################

    verify:forge:
        desc: Verify contract source using Foundry (e.g. task verify -- <network name> <contract-address> [<path>:<contractname>])
        # TODO: add summary with examples
        aliases:
            - verify
        vars:
            NETWORK:
                sh: task internal:ensure-arg -- "network name" {{index .CLI_ARGS_LIST 0}}
            SC_ADDR:
                sh: task internal:ensure-arg -- "address" {{index .CLI_ARGS_LIST 1}}
            EXT_ARGS: '{{slice .CLI_ARGS_LIST 2 | join " "}}'
            RPC: "${{.NETWORK}}_RPC"
            API_KEY: "${{.NETWORK}}_API_KEY"
            CHAINID: "${{.NETWORK}}_CHAINID"
        cmd: forge verify-contract -c {{.CHAINID}} -e {{.API_KEY}} -r {{.RPC}} --compiler-version {{.SOLC_VERSION}} --watch {{.SC_ADDR}} {{.EXT_ARGS}}

    #######################################################
    # Wallet
    #######################################################

    wallet:new:
        desc: Create a new local private key in .keystore
        silent: true
        deps:
            - internal:ensure-local-keystore
        vars:
            WALLET_NAME:
                sh: task internal:ensure-arg -- "wallet name" {{index .CLI_ARGS_LIST 0}}
            SHEFT_NEW_WALLET_PW_RAW: '{{.SHEFT_NEW_WALLET_PW_RAW | default ""}}'
            PW_RAW: "{{if gt (len .SHEFT_NEW_WALLET_PW_RAW) 0}}--unsafe-password {{.SHEFT_NEW_WALLET_PW_RAW}}{{end}}"
        cmd: cast wallet new {{.PW_RAW}} .keystore {{.WALLET_NAME}}

    wallet:new:dry:
        desc: Generate a new private key and and address without storing
        silent: true
        aliases:
            - wallet:dry
        deps:
            - internal:ensure-local-keystore
        cmd: cast wallet new

    wallet:mnemonic:
        desc: Generate a random BIP39 mnemonic phrase without storing the accounts
        aliases:
            - wallet:mn
        silent: true
        cmd: cast wallet new-mnemonic

    wallet:import:pk:
        desc: Import a private key into local keystore
        silent: true
        aliases:
            - wallet:ipk
        deps:
            - internal:ensure-local-keystore
        vars:
            WALLET_NAME:
                sh: task internal:ensure-arg -- "wallet name" {{index .CLI_ARGS_LIST 0}}
        cmd: cast wallet import -k .keystore -i {{.WALLET_NAME}}

    wallet:import:mnemonic:
        desc: Import a selected index off mnemonic seed into local keystore
        silent: true
        aliases:
            - wallet:imn
        deps:
            - internal:ensure-local-keystore
        vars:
            WALLET_NAME:
                sh: task internal:ensure-arg -- "wallet name" {{index .CLI_ARGS_LIST 0}}
        cmds:
            - defer: rm -fr .keystore/.tmp.mn .keystore/.tmp.mni
            - task: internal:install:deps:ts
            - task: internal:run:ts
              vars:
                TS_FILE: src/ts/prompt-secret.ts
            - cast wallet import -k .keystore --mnemonic .keystore/.tmp.mn --mnemonic-index $(cat .keystore/.tmp.mni) {{.WALLET_NAME}}

    wallet:list:
        desc: List local wallet keys
        silent: true
        aliases:
            - wallet:ls
        deps:
            - internal:ensure-local-keystore
        cmd: cast wallet ls --dir .keystore

    wallet:address:
        desc: Get the address of a local private key from keystore
        silent: true
        deps:
            - internal:ensure-local-keystore
        aliases:
            - wallet:addr
        vars:
            WALLET_NAME:
                sh: task internal:ensure-arg -- "wallet name" {{index .CLI_ARGS_LIST 0}}
        cmd: cast wallet address --keystore ".keystore/{{.WALLET_NAME}}"

    wallet:changepass:
        desc: Change a local wallet's password
        silent: true
        deps:
            - internal:ensure-local-keystore
        aliases:
            - wallet:cp
        vars:
            WALLET_NAME:
                sh: task internal:ensure-arg -- "wallet name" {{index .CLI_ARGS_LIST 0}}
        cmd: cast wallet cp -k .keystore {{.WALLET_NAME}}

    wallet:privatekey:
        desc: Show a local wallet's private key
        silent: true
        deps:
            - internal:ensure-local-keystore
        aliases:
            - wallet:pk
        vars:
            WALLET_NAME:
                sh: task internal:ensure-arg -- "wallet name" {{index .CLI_ARGS_LIST 0}}
        cmd: cast wallet dk -k .keystore {{.WALLET_NAME}}

    #######################################################
    # Coverage Report
    #######################################################

    ensure-cov-tools:
        internal: true
        silent: true
        preconditions:
            - sh: command -v lcov >/dev/null 2>&1
              msg: lcov is not installed
            - sh: command -v genhtml >/dev/null 2>&1
              msg: genhtml is not installed
        cmd: mkdir -p coverage

    cover:sol:
        desc: Generate coverage report. Accepts CLI args for `forge coverage`
        aliases:
            - cover
        sources:
            - src/contracts/**/*.sol
            - test/foundry/**/*.sol
        generates:
            - coverage/**/*
        deps:
            - internal:ensure-cov-tools
        cmds:
            - forge coverage --report lcov --report summary --report debug --ffi --report-file coverage/lcov.info {{.CLI_ARGS}}
            - genhtml coverage/lcov.info --output-dir coverage

    host:cover:
        desc: Host coverage report via npm package `http-server`. Accepts CLI args for `http-server`
        cmds:
            - task cover:sol
            - [[.Computed.jpm_x]] http-server coverage {{.CLI_ARGS}}

    #######################################################
    # Utility
    #######################################################

    docs:
        desc: Generate Solidity docs from natspec comments in source codes
        cmd: forge doc -o docs -b -j 0 {{.CLI_ARGS}}

    host:docs:
        desc: Host docs
        deps:
            - build:sol
        cmd: task docs -- -s --open

    sort-package.json:
        desc: Sorts root package.json
        cmd: [[.Computed.jpm_x]] sort-package-json package.json

    #######################################################
    # Clean
    #######################################################

    clean:wallets:
        desc: Remove local ./keystore
        prompt: This action will remove your wallets in ./keystore. Are you sure?
        cmd: rm -fr .keystore

    clean:build:
        desc: Remove all Solidity cache and artifacts
        cmd: rm -fr artifacts cache typechain

    clean:coverage:
        desc: Remove Foundry generated ./coverage
        cmd: rm -fr coverage

    clean:docs:
        desc: Remove Foundry generated ./docs
        cmd: rm -fr docs

    clean:npm:
        desc: Remove ./node_modules and ./package/node_modules
        cmd: rm -fr node_modules package/node_modules

    clean:all:
        desc: Clears all cache and artifacts and docs and everything in general
        silent: true
        aliases:
            - clean
        cmds:
            - task clean:build
            - task clean:coverage
            - task clean:docs
            - task clean:npm

includes:
    internal:
        taskfile: tasks/internal.yaml
        dir: .

[[ if .Scaffold.should_package ]]
    package:
        taskfile: ./package
        dir: ./package
        internal: true
[[ end ]]