version: "3.44"

tasks:
    deps:
        desc: Install dependencies
        sources:
            - package.json
        generates:
            - bun.lock
        cmd: bun install {{.CLI_ARGS}}

    clean:
        desc: Rmove ./dist directory
        cmd: rm -fr dist
